interface/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path

from interface import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "assignment/<course_pk>/<assignment_pk>/upload/",
        views.upload,
        name="upload",
    ),
    path("submission/", views.submission_list, name="submission_list"),
    path("homepage/", views.homepage, name="homepage"),
    path(
        "submission/<int:pk>/",
        views.submission_result,
        name="submission_result",
    ),
    path("submission/<int:pk>/done", views.done),
    path("submission/<int:pk>/review", views.review),
    path("submission/<int:pk>/download", views.download),
    path("submission/<int:pk>/rerun", views.rerun_submission),
    path("submission/<int:pk>/recompute", views.recompute_score),
    path("alive/", views.alive),
    path("logout/", views.logout_view, name="logout"),
    path("", views.login_view, name="login"),
    path(
        "assignment/<course_pk>/<assignment_pk>",
        views.assignment_users_list,
        name="subs_for_assignment",
    ),
    path(
        "assignment/<course_pk>/<assignment_pk>/reveal",
        views.reveal,
        name="reveal",
    ),
    path(
        "assignment/<course_pk>/<assignment_pk>/user/<username>",
        views.subs_for_user,
        name="subs_for_user",
    ),
    path("mysubmissions/<username>", views.user_page, name="user_page"),
    path(
        "submission/<int:pk>/<path:filename>/",
        views.code_view,
        name="code_view",
    ),
]

if settings.PROFILE:
    urlpatterns += [re_path(r"^silk/", include("silk.urls", namespace="silk"))]

interface/models.py
import datetime
import logging
import re
from collections import OrderedDict
from urllib.parse import urljoin

import jwt
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import pre_save
from simple_history.models import HistoricalRecords

import interface.backend.minio_api as storage
from interface import signals
from interface.backend.submission.submission_scheduler import SubmissionScheduler

log = logging.getLogger(__name__)


class ActionLog(models.Model):
    timestamp = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    action = models.CharField(max_length=256)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    def __str__(self):
        return f"{self.user}: {self.action}"


class Course(models.Model):
    name = models.CharField(max_length=256, blank=False)
    teaching_assistants = models.ManyToManyField(User, blank=True)
    history = HistoricalRecords()

    def __str__(self):
        return f"{self.name}"


def get_default_penalty_info():
    return {
        "penalty_weights": [],
        "holiday_start": [],
        "holday_finish": [],
    }


def get_default_vm_info():
    return {"nr_cpus": 1, "memory": 512}


class Assignment(models.Model):
    LANG_C = "c"
    LANG_PYTHON = "py"
    LANG_JAVA = "java"

    # This is a maping from file format to what moss expects
    # as input when choosing a language
    LANG_CHOICES = OrderedDict(
        [(LANG_C, "c"), (LANG_PYTHON, "python"), (LANG_JAVA, "java")],
    )

    course = models.ForeignKey(Course, on_delete=models.PROTECT, null=True)
    name = models.CharField(max_length=256, blank=False)
    max_score = models.IntegerField(default=100)
    deadline_soft = models.DateTimeField()
    deadline_hard = models.DateTimeField()
    min_time_between_uploads = models.IntegerField(default=60)
    repo_url = models.CharField(max_length=256, blank=True)
    repo_branch = models.CharField(max_length=256, blank=True)
    repo_path = models.CharField(max_length=256, blank=True)
    language = models.CharField(
        max_length=32,
        choices=list(LANG_CHOICES.items()),
        default=LANG_C,
    )

    image_path = models.CharField(max_length=256, blank=False, default="NA")
    penalty_info = models.JSONField(default=get_default_penalty_info)
    vm_options = models.JSONField(default=get_default_vm_info)

    history = HistoricalRecords()
    hidden_score = models.BooleanField(default=True)
    hide = models.BooleanField(null=False, default=False)
    assignment_on = models.BooleanField(null=False, default=False)

    def __str__(self):
        return f"{self.full_code} {self.name}"

    def clean(self):
        penalty_weights = self.penalty_info["penalty_weights"]
        if not isinstance(penalty_weights, list) or not all(
            isinstance(x, (float, int)) for x in penalty_weights
        ):
            raise ValidationError(
                "Penalty weights should be a list of integer/floats",
            )

        if len(penalty_weights) != (self.deadline_hard - self.deadline_soft).days:
            raise ValidationError(
                "Number of penalty weights should be == days from soft " "to hard deadline",
            )

    @property
    def full_code(self):
        return f"{self.course.pk}-{self.pk}"

    @property
    def is_active(self):
        now = datetime.datetime.now(datetime.timezone.utc)
        diff = self.deadline_hard - now

        return diff.total_seconds() > 0

    def url_for(self, filename):
        m = re.match(
            r"https://github.com/(?P<org>[^/]+)/(?P<repo>[^/]+)/?$",
            self.repo_url,
        )

        org, repo = m.groups()

        url_base = f"https://raw.githubusercontent.com/{org}/{repo}/"
        branch = self.repo_branch or "master"
        path = f"{self.repo_path}/" if self.repo_path else ""
        return urljoin(url_base, f"{branch}/{path}{filename}")

    def refresh_submission_penalty(self):
        for submission in self.submission_set.all():
            submission.penalty = None
            submission.save()


class Submission(models.Model):
    """Model for a homework submission

    Attributes:
    username -- the user id provided by the LDAP
    assignment_id -- class specific, will have the form
                     `{course_name}_{homework_id}` for example pc_00
    stdout -- the output message of the checker
    stderr -- the error message of the checker
    score -- the score of the submission given by the checker
    review_score -- score set by the assignment reviewer
    total_score -- score + review_score
    max_score -- the maximum score for the submission
    archive_size -- archive, sent to server, size in KB
    """

    STATE_NEW = "new"
    STATE_RUNNING = "running"
    STATE_DONE = "done"
    STATE_QUEUED = "queued"
    STATE_ERROR = "error"

    STATE_CHOICES = OrderedDict(
        [
            (STATE_NEW, "New"),
            (STATE_RUNNING, "Running"),
            (STATE_DONE, "Done"),
            (STATE_QUEUED, "Queue"),
            (STATE_ERROR, "Error"),
        ],
    )

    assignment = models.ForeignKey(
        Assignment,
        on_delete=models.CASCADE,
        null=True,
    )
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    stdout = models.TextField(max_length=32768, default="", blank=True)
    stderr = models.TextField(max_length=32768, default="", blank=True)
    review_message = models.TextField(max_length=4096, default="", blank=True)
    state = models.CharField(
        max_length=32,
        choices=list(STATE_CHOICES.items()),
        default=STATE_QUEUED,
    )
    timestamp = models.DateTimeField(null=True, auto_now_add=True)

    review_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
    )
    total_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
    )
    score = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    penalty = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    archive_size = models.IntegerField(null=True)
    evaluator_job_id = models.IntegerField(null=True)

    history = HistoricalRecords()

    def __str__(self):
        return f"#{self.pk} by {self.user}"

    def update_state(self):
        if self.state in [self.STATE_DONE, self.STATE_ERROR] or self.evaluator_job_id is None:
            return

        state = SubmissionScheduler.evaluator.update(self)
        if state != self.state:
            self.state = state
            self.changeReason = f"Update state to {state}"
            self.save(update_fields=["state"])

            if self.state in [self.STATE_DONE, self.STATE_ERROR]:
                SubmissionScheduler.get_instance().done_evaluation(self)

    def download(self, buff):
        storage.download_buffer(f"{self.pk}.zip", buff)

    def get_script_url(self):
        return self.assignment.url_for("checker.sh")

    def get_artifact_url(self):
        return self.assignment.url_for("artifact.zip")

    @property
    def state_label(self):
        return self.STATE_CHOICES[self.state]

    def get_url(self):
        return storage.get_link(f"{self.pk}.zip")

    def evaluate(self):
        SubmissionScheduler.get_instance().add_submission(self)

    def generate_jwt(self):
        """Generates a JWT token that the checker will use
        when it calls back with the result
        """
        return jwt.encode({"data": str(self.pk)}, settings.SECRET_KEY, algorithm="HS256")

    def verify_jwt(self, message):
        """Verify that the token was generated by us
        so we can trust the checker result
        """
        if not message:
            return False
        try:
            decoded_message = jwt.decode(
                message,
                settings.SECRET_KEY,
                algorithms=["HS256"],
            )

            return decoded_message["data"] == str(self.id)
        except jwt.DecodeError:
            log.debug("Invalid JWT token: %s", message)
            return False


pre_save.connect(signals.update_total_score, sender=Submission)

interface/forms.py
from django import forms
from django.conf import settings
from django.template.defaultfilters import filesizeformat


class UploadFileForm(forms.Form):
    file = forms.FileField(
        label="Select archive",
        widget=forms.FileInput(attrs={"accept": "application/zip"}),
    )

    def clean_file(self):
        data = self.cleaned_data["file"]

        if data.size >= settings.FILE_UPLOAD_MAX_MEMORY_SIZE:
            raise forms.ValidationError(
                "Keep files below " f"{filesizeformat(settings.FILE_UPLOAD_MAX_MEMORY_SIZE)}",
            )

        return data


class LoginForm(forms.Form):
    username = forms.CharField(label="Username")
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

interface/templates/interface/code_view.html
{% extends "interface/generics/base.html" %}

<script type="text/javascript">
    $('.accordian-body').on('show.bs.collapse', function () {
        $(this).closest("table")
            .find(".collapse.in")
            .not(this)
            .collapse('toggle')
    });
</script>
<style>
.hiddenRow {
    padding: 0 !important;
}
</style>

{% block body_content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-3">
            <div>
                {% if user in sub.assignment.course.teaching_assistants.all %}
                    <p>
                        <button type="button" class="btn btn-primary btn-sm mr-1" data-toggle="modal" data-target="#review" data-id="{{ sub.id }}">Finish review</button>
                    </p>
                {% endif %}
            </div>
                {% with dict=tree.items template="interface/tree_view.html" %}
                    {% include template %}
                {% endwith %}
        </div>
        <div class="col-lg-9">
            <div>
                {% if not file_exists %}
                    {{ file_content }}
                {% else %}
                    <table class="table table-hover table-sm table-borderless" data-toggle="table" style="border-collapse: collapse;">
                        <thead>
                            <tr>
                                <th>
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for line in file_content %}
                            <tr data-toggle="collapse" data-target="#demo_{{ forloop.counter }}" style="line-height: 1em;">
                                <td style="padding:0;height: 1px;"> {{ forloop.counter }} </td>
                                <td style="padding:0;height: 1px;">
                                    {% with forloop.counter as index %}
                                    {% if sub.comments|with_path:path|with_line:index %}
                                        <div style="background-color: #FFCCCB;padding: 0;;white-space: pre;font-family: monospace;">{{ line }}</div>
                                    {% else %}
                                        <div style="padding: 0;white-space: pre;font-family: monospace;">{{ line }}</div>
                                    {% endif %}
                                    {% endwith %}
                                </td>
                            </tr>
                            <tr>
                                <td colspan="6" class="hiddenRow">
                                    <div class="accordian-body collapse" id="demo_{{ forloop.counter }}">
                                        <div class="tab-pane" id="add-comment">
                                            {% with forloop.counter as index %}
                                                {% for comment in path_comments %}
                                                    {% if comment.line == index %}
                                                    <div class="post-comment">
                                                        <p class="info">
                                                            Comment {{ forloop.counter }} by {{ comment.user }}
                                                            {{ comment.created }}
                                                        </p>
                                                        {{ comment.text|linebreaks }}
                                                    </div>
                                                    {% endif %}
                                                {% empty %}
                                                <p>There are no comments yet.</p>
                                                {% endfor %}
                                            {% endwith %}
                                            {% if new_comment %}
                                                <h2>Your comment has been added.</h2>
                                            {% else %}
                                                <form action="." method="post" class="form-horizontal" id="commentForm" role="form">
                                                    <div class="form-group">
                                                        <div class="col-sm-10">
                                                                {% csrf_token %}
                                                                {{ form.as_p }}
                                                        </div>
                                                    </div>
                                                    <input type="hidden" name="line" value="{{ forloop.counter }}">
                                                    <div class="form-group">
                                                        <div class="col-sm-offset-2 col-sm-10">
                                                            <p><input class="btn btn-success btn-circle text-uppercase" type="submit" value="Add comment"></p>
                                                        </div>
                                                    </div>
                                                </form>
                                            {% endif %}
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
                </div>
        </div>
    </div>
</div>

{% include "interface/generics/review_modal.html" %}

{% endblock %}

interface/templates/interface/code_view_homepage.html
{% extends "interface/generics/base.html" %}

{% block body_content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-3">
            {% with dict=tree.items template="interface/tree_view.html" %}
                {% include template %}
            {% endwith %}
        </div>
        <div class="col-lg-9">
            <div class="row align-items-center">
                <div class="col-lg-2"></div>
                <div class="col-lg-9">
                    <pre>
                        /^--^\     /^--^\     /^--^\
                        \____/     \____/     \____/
                       /      \   /      \   /      \
                      |        | |        | |        |
                       \__  __/   \__  __/   \__  __/
  |^|^|^|^|^|^|^|^|^|^|^|^\ \^|^|^|^/ /^|^|^|^|^\ \^|^|^|^|^|^|^|^|^|^|^|^|
  | | | | | | | | | | | | |\ \| | |/ /| | | | | | \ \ | | | | | | | | | | |
  | | | | | | | | | | | | / / | | |\ \| | | | | |/ /| | | | | | | | | | | |
  | | | | | | | | | | | | \/| | | | \/| | | | | |\/ | | | | | | | | | | | |
  #########################################################################
  | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |
  | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |

              </pre>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

interface/templates/interface/homepage.html
{% extends "interface/generics/base.html" %}

{% block body_content %}
  <div class="container">
    <div class="btn-group" style="width: 100%;">
      <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 100%;">
        Select course
      </button>

      <div class="dropdown-menu" style="width: 100%;">
        {% for course in courses %}
          <a class="dropdown-item" href="?course={{ course.id }}">{{ course.name }}</a>
        {% endfor %}
      </div>
    </div>

    <ul>
      {% for assignment in assignments %}
        <li>
          {{ assignment.name }}:
          {% if assignment.is_active and assignment.assignment_on or assignment.is_active and user in assignment.course.teaching_assistants.all %}
            <a href="{% url 'upload' assignment.course.pk assignment.pk %}">Upload</a>,
          {% endif %}
          <a href="{% url 'subs_for_assignment' assignment.course.pk assignment.pk %}">Results</a>
        </li>
      {% endfor %}
    </ul>

  </div>
{% endblock %}

interface/templates/interface/login.html
{% extends "interface/generics/base.html" %}

{% block body_content %}
  <div class="container-fluid row">
    <div class="col-md-6 offset-md-3">
      <h1>vmchecker v2</h1>

      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Login</button>
      </form>
    </div>
  </div>
{% endblock %}

interface/templates/interface/submission.html
<!doctype html>
<html lang='en'>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <title>VMCK</title>
    </head>

    <body>
        <div class="container">
            <a class="btn btn-primary" href='{{ upload_url }}'>Upload submission</a>
            <a class="btn btn-primary" href='{{ submission_list_url }}'>List submissions</a>
            <p>Submission id: {{ sub.id }}</p>
            <p>Your score is: {{ sub.score }}/{{ sub.max_score }}</p>
            <p>The output is:</p>
            <pre><samp>{{ sub.message }}</samp></pre>
        </div>
    </body>
</html>

interface/templates/interface/submission_list.html
{% extends "interface/generics/base.html" %}

{% block body_content %}
  <div class="container">
    <div class="row mt-2">
      <table class="table table-striped table-bordered table-sm">
        <caption>Submission list</caption>

        <thead>
          <tr>
            <th scope="col">User id</th>
            <th scope="col">Submission id</th>
            <th scope="col">Homework id</th>
            <th scope="col">Archive size</th>
            <th scope="col">Preliminary score</th>
            <th scope="col">Status</th>
          </tr>
        </thead>

        <tbody>
          {% for sub in submissions %}
            <tr>
              <td>{{ sub.user.username }}</td>
              <td><a href="{{ sub_base_url }}{{ sub.pk }}">{{ sub.pk }}</a></td>
              <td>{{ sub.assignment.full_code }}</td>
              <td>{{ sub.archive_size|filesizeformat }}</td>
              {% if sub.user.username == user.username or user in sub.assignment.course.teaching_assistants.all %}
                <td>{{ sub.score }}</td>
              {% else %}
              <td> N/A </td>
              {% endif %}
              <td>{{ sub.get_state_display }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="rowf text-center">
      {% if submissions.has_previous %}
        <a class="btn btn-primary" href='?page={{ submissions.previous_page_number }}'>Prev</a>
      {% endif %}

      <span class="current">
        Page {{ submissions.number }} of {{ submissions.paginator.num_pages }}.
      </span>

      {% if submissions.has_next %}
        <a class="btn btn-primary" href='?page={{ submissions.next_page_number }}'>Next</a>
      {% endif %}
    </div>

    </div>
{% endblock %}

interface/templates/interface/submission_result.html
{% extends "interface/generics/base.html" %}

{% block body_content %}
<div class="container">

  <h1>Submission {{ sub }} ({{ sub.state }})</h1>

  <div class="btn-group" role="group" aria-label="Actions">

    {% if user == sub.user or user in sub.assignment.course.teaching_assistants.all %}
      <form action="download">
        {% csrf_token %}
        <input formmethod="post" class="btn btn-primary btn-sm mr-1" type="submit" value="Download archive">
      </form>
    {% endif %}

    {% if user in sub.assignment.course.teaching_assistants.all %}
      <form action="rerun">
        {% csrf_token %}
        <input formmethod="post" class="btn btn-primary btn-sm mr-1" type="submit" value="Rerun submission">
      </form>
      {% endif %}

      {% if user in sub.assignment.course.teaching_assistants.all %}
      <form action="recompute">
        {% csrf_token %}
        <input formmethod="post" class="btn btn-primary btn-sm mr-1" type="submit" value="Recompute score">
      </form>
      {% endif %}

      {% if user == sub.user or user in sub.assignment.course.teaching_assistants.all %}
      <form>
        <button class="btn btn-primary btn-sm mr-1" formaction="{% url 'code_view_homepage' sub.pk %}">Start review</button>
      </form>
      {% endif %}
    </div>

  {% if sub.state == sub.STATE_DONE %}

    {% if not sub.assignment.hidden_score or user in sub.assignment.course.teaching_assistants.all %}

      <p>Final score: {{ sub.total_score }}/{{ sub.assignment.max_score }}</p>

      {% if sub.review_message and sub.user.username == user.username %}
        <h2>Review</h2>
        <div class="card">
          <div class="card-body">
            <pre><code>{{ sub.review_message }}</code></pre>
          </div>
        </div>
      {% endif %}

    {% else %}
      <p>Score: N/A </p>

    {% endif %}

    {% if sub.user.username == user.username or user in sub.assignment.course.teaching_assistants.all %}
      <h2>Output</h2>
      <div class="card">
        <div class="card-body">
          <pre><code>{{ sub.stdout }}</code></pre>
        </div>
      </div>
      <p>Preliminary score: {{ sub.preliminary_score }}/{{ sub.assignment.max_score }}</p>
    {% endif %}
  {% else %}

    <h2>Fortune teller</h2>
    <div class="card">
      <div class="card-body">
          <pre><code>{{ fortune }}</code></pre>
      </div>
    </div>

    <p>Submission is being evaluated, check again later.</p>

  {% endif %}

</div>



{% endblock %}

interface/templates/interface/subs_for_user.html
{% extends "interface/generics/base.html" %}

{% block body_content %}
  <div class="container">
    <h1>{{ assignment.course.name }} &mdash; {{ assignment.name }}</h1>
    <h2>{{ user_assignment }}</h2>

    <table class="table table-striped table-bordered table-sm mt-2">
      <thead>
        <tr>
          <th scope="col">Time</th>
          <th scope="col">Submission id</th>
          <th scope="col">Score</th>
          <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
        {% for sub in submissions %}
          <tr>
            <td>{{ sub.timestamp|date:'Y-m-d H:i' }}</td>
            <td><a href="{% url 'submission_result' sub.pk %}">{{ sub.pk }}</a></td>
            {% if not sub.assignment.hidden_score %}
              <td>{{ sub.total_score }}/{{ sub.assignment.max_score }}</td>
            {% else %}
              <td> N/A </td>
            {% endif %}
            <td>{{ sub.get_state_display }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <div class="rowf text-center">
      {% if submissions.has_previous %}
        <a class="btn btn-primary" href='?page={{ submissions.previous_page_number }}'>Prev</a>
      {% endif %}

      <span class="current">
        Page {{ submissions.number }} of {{ submissions.paginator.num_pages }}.
      </span>

      {% if submissions.has_next %}
        <a class="btn btn-primary" href='?page={{ submissions.next_page_number }}'>Next</a>
      {% endif %}
    </div>

  </div>
{% endblock %}

interface/templates/interface/user_page.html
{% extends "interface/generics/base.html" %}

{% block body_content %}
  <div class="container">
    <h1> Submissions {{ user.username }} </h1>
        <table class="table table-striped table-bordered table-sm">
            <thead class="text-center">
            <tr>
                <th scope="col">Submission id</th>
                <th scope="col">Assignment</th>
                <th scope="col">Course</th>
                <th scope="col">Time</th>
                <th scope="col">Final score</th>
                <th scope="col">Status</th>
                <th scope="col">Reviewed</th>
            </tr>
            </thead>
            <tbody>
            {% for sub in submissions %}
                <tr>
                <td><a href="{% url 'submission_result' sub.pk %}">{{sub.pk}}</a></td>
                <td>{{ sub.assignment.name }}</td>
                <td>{{ sub.assignment.course.name }}</td>
                <td>{{ sub.timestamp|date:'Y-m-d H:i' }}</td>
                {% if not sub.assignment.hidden_score %}
                    <td>{{ sub.total_score }}</td>
                {% else %}
                    <td> N/A </td>
                {% endif %}
                <td>{{ sub.get_state_display }}</td>

                <td class="text-center">
                    {% if sub.review_message %}
                        &#x2713;
                    {% endif %}
                </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="rowf text-center">
            {% if submissions.has_previous %}
              <a class="btn btn-primary" href='?page={{ submissions.previous_page_number }}'>Prev</a>
            {% endif %}

            <span class="current">
              Page {{ submissions.number }} of {{ submissions.paginator.num_pages }}.
            </span>

            {% if submissions.has_next %}
              <a class="btn btn-primary" href='?page={{ submissions.next_page_number }}'>Next</a>
            {% endif %}
          </div>
  </div>
{% endblock %}

interface/templates/interface/users_list.html
{% extends "interface/generics/base.html" %}

{% block body_content %}
  <div class="container">
    <h1>{{ assignment.course.name }} / {{ assignment.name }}</h1>

    <h5><b>Deadline soft:</b> {{ assignment.deadline_soft|date:'Y-m-d H:i' }}</h5>
    <h5><b>Deadline hard:</b> {{ assignment.deadline_hard|date:'Y-m-d H:i' }}</h5>
    <h5><b>Scor maxim:</b> {{ assignment.max_score }}</h5>
    {% if user in assignment.course.teaching_assistants.all %}
      <form action="reveal">
        {% csrf_token %}
        <a formmethod="post" href="{% url 'reveal' assignment.course.pk assignment.pk %}" class="btn btn-primary btn-sm mr-1" type="submit">Reveal</a>
      </form>
    {% endif %}

    <table class="table table-striped table-bordered table-sm">
      <thead class="text-center">
        <tr>
          <th scope="col">Username</th>
          <th scope="col">Time</th>
          <th scope="col">Preliminary score</th>
          <th scope="col">Final score</th>
          <th scope="col">Status</th>
          <th scope="col">Submission id</th>
          <th scope="col">Reviewed</th>
        </tr>
      </thead>
      <tbody>
        {% for sub in submissions %}
          <tr>
            <td><a href="{% url 'subs_for_user' sub.assignment.course.pk sub.assignment.pk sub.user.username %}">{{ sub.user.username }}</a></td>
            <td>{{ sub.timestamp|date:'Y-m-d H:i' }}</td>
            <td>{{ sub.score }}</td>
            {% if not sub.assignment.hidden_score %}
              {% if sub.user.username == user.username or user in sub.assignment.course.teaching_assistants.all %}
                <td>{{ sub.total_score }}/{{ sub.assignment.max_score }}</td>
              {% else %}
                <td> N/A </td>
              {% endif %}
            {% else %}
              <td> N/A </td>
            {% endif %}
            <td>{{ sub.get_state_display }}</td>
            <td><a href="{% url 'submission_result' sub.pk %}">{{sub.pk}}</a></td>
            <td class="text-center">
                {% if user.username == sub.user.username or user in sub.assignment.course.teaching_assistants.all %}
                  {% if sub.review_message %}
                    &#x2713;
                  {% endif %}
                {% endif %}
            </td>
          </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="rowf text-center">
      {% if submissions.has_previous %}
        <a class="btn btn-primary" href='?page={{ submissions.previous_page_number }}'>Prev</a>
      {% endif %}

      <span class="current">
        Page {{ submissions.number }} of {{ submissions.paginator.num_pages }}.
      </span>

      {% if submissions.has_next %}
        <a class="btn btn-primary" href='?page={{ submissions.next_page_number }}'>Next</a>
      {% endif %}
    </div>

  </div>
{% endblock %}